spring.application.name=tournament

# SQLite database
spring.datasource.url=jdbc:sqlite:tournament.db
spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
driverClassName=org.sqlite.JDBC
url=jdbc:sqlite:memory:myDb?cache=shared
username=abe
password=abe
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true
# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/master.xml

spring.jpa.hibernate.ddl-auto=update

# Static content will be served from /static/
spring.web.resources.static-locations=classpath:/static/
